var countries = [{
    name: 'Country3',
    states: [{
        name: 'c3_State3',
        cities: [{
            name: 'c3_s3_City4',
            population: '427280'
        }, {
            name: 'c3_s3_City1',
            population: '350935'
        }, {
            name: 'c3_s3_City3',
            population: '300615'
        }, {
            name: 'c3_s3_City2',
            population: '169847'
        }]
    }, {
        name: 'c3_State4',
        cities: [{
            name: 'c3_s4_City3',
            population: '14406'
        }, {
            name: 'c3_s4_City1',
            population: '101630'
        }, {
            name: 'c3_s4_City2',
            population: '207632'
        }, {
            name: 'c3_s4_City4',
            population: '485489'
        }]
    }, {
        name: 'c3_State1',
        cities: [{
            name: 'c3_s1_City3',
            population: '429861'
        }, {
            name: 'c3_s1_City1',
            population: '494513'
        }, {
            name: 'c3_s1_City2',
            population: '467491'
        }, {
            name: 'c3_s1_City4',
            population: '59288'
        }]
    }, {
        name: 'c3_State2',
        cities: [{
            name: 'c3_s2_City3',
            population: '226881'
        }, {
            name: 'c3_s2_City2',
            population: '157207'
        }, {
            name: 'c3_s2_City4',
            population: '142962'
        }, {
            name: 'c3_s2_City1',
            population: '13510'
        }]
    }, {
        name: 'c3_State5',
        cities: [{
            name: 'c3_s5_City1',
            population: '386863'
        }, {
            name: 'c3_s5_City3',
            population: '395835'
        }, {
            name: 'c3_s5_City4',
            population: '272301'
        }, {
            name: 'c3_s5_City2',
            population: '467014'
        }]
    }]
}, {
    name: 'Country2',
    states: [{
        name: 'c2_State3',
        cities: [{
            name: 'c2_s3_City3',
            population: '317242'
        }, {
            name: 'c2_s3_City4',
            population: '66158'
        }, {
            name: 'c2_s3_City2',
            population: '11574'
        }, {
            name: 'c2_s3_City1',
            population: '98596'
        }]
    }, {
        name: 'c2_State1',
        cities: [{
            name: 'c2_s1_City4',
            population: '398891'
        }, {
            name: 'c2_s1_City2',
            population: '118922'
        }, {
            name: 'c2_s1_City1',
            population: '212200'
        }, {
            name: 'c2_s1_City3',
            population: '115078'
        }]
    }, {
        name: 'c2_State4',
        cities: [{
            name: 'c2_s4_City1',
            population: '444322'
        }, {
            name: 'c2_s4_City2',
            population: '197740'
        }, {
            name: 'c2_s4_City3',
            population: '79272'
        }, {
            name: 'c2_s4_City4',
            population: '436312'
        }]
    }, {
        name: 'c2_State5',
        cities: [{
            name: 'c2_s5_City2',
            population: '456248'
        }, {
            name: 'c2_s5_City4',
            population: '84353'
        }, {
            name: 'c2_s5_City3',
            population: '207747'
        }, {
            name: 'c2_s5_City1',
            population: '446666'
        }]
    }, {
        name: 'c2_State2',
        cities: [{
            name: 'c2_s2_City1',
            population: '62728'
        }, {
            name: 'c2_s2_City2',
            population: '215059'
        }, {
            name: 'c2_s2_City3',
            population: '150894'
        }, {
            name: 'c2_s2_City4',
            population: '254818'
        }]
    }]
}, {
    name: 'Country1',
    states: [{
        name: 'c1_State4',
        cities: [{
            name: 'c1_s4_City4',
            population: '104040'
        }, {
            name: 'c1_s4_City2',
            population: '216241'
        }, {
            name: 'c1_s4_City1',
            population: '398554'
        }, {
            name: 'c1_s4_City3',
            population: '127834'
        }]
    }, {
        name: 'c1_State1',
        cities: [{
            name: 'c1_s1_City1',
            population: '256153'
        }, {
            name: 'c1_s1_City2',
            population: '335863'
        }, {
            name: 'c1_s1_City4',
            population: '78786'
        }, {
            name: 'c1_s1_City3',
            population: '345204'
        }]
    }, {
        name: 'c1_State5',
        cities: [{
            name: 'c1_s5_City4',
            population: '238909'
        }, {
            name: 'c1_s5_City2',
            population: '167365'
        }, {
            name: 'c1_s5_City3',
            population: '52912'
        }, {
            name: 'c1_s5_City1',
            population: '471809'
        }]
    }, {
        name: 'c1_State3',
        cities: [{
            name: 'c1_s3_City4',
            population: '367380'
        }, {
            name: 'c1_s3_City3',
            population: '255325'
        }, {
            name: 'c1_s3_City2',
            population: '220855'
        }, {
            name: 'c1_s3_City1',
            population: '259938'
        }]
    }, {
        name: 'c1_State2',
        cities: [{
            name: 'c1_s2_City3',
            population: '10673'
        }, {
            name: 'c1_s2_City2',
            population: '360391'
        }, {
            name: 'c1_s2_City1',
            population: '260623'
        }, {
            name: 'c1_s2_City4',
            population: '159880'
        }]
    }]
}, {
    name: 'Country4',
    states: [{
        name: 'c4_State5',
        cities: [{
            name: 'c4_s5_City1',
            population: '9721'
        }, {
            name: 'c4_s5_City3',
            population: '109564'
        }, {
            name: 'c4_s5_City2',
            population: '250462'
        }, {
            name: 'c4_s5_City4',
            population: '32599'
        }]
    }, {
        name: 'c4_State2',
        cities: [{
            name: 'c4_s2_City3',
            population: '200598'
        }, {
            name: 'c4_s2_City4',
            population: '34599'
        }, {
            name: 'c4_s2_City2',
            population: '77855'
        }, {
            name: 'c4_s2_City1',
            population: '19403'
        }]
    }, {
        name: 'c4_State1',
        cities: [{
            name: 'c4_s1_City3',
            population: '385666'
        }, {
            name: 'c4_s1_City2',
            population: '357294'
        }, {
            name: 'c4_s1_City4',
            population: '279114'
        }, {
            name: 'c4_s1_City1',
            population: '304547'
        }]
    }, {
        name: 'c4_State4',
        cities: [{
            name: 'c4_s4_City4',
            population: '484152'
        }, {
            name: 'c4_s4_City2',
            population: '297589'
        }, {
            name: 'c4_s4_City3',
            population: '356328'
        }, {
            name: 'c4_s4_City1',
            population: '61451'
        }]
    }, {
        name: 'c4_State3',
        cities: [{
            name: 'c4_s3_City1',
            population: '484443'
        }, {
            name: 'c4_s3_City3',
            population: '448202'
        }, {
            name: 'c4_s3_City4',
            population: '332054'
        }, {
            name: 'c4_s3_City2',
            population: '142069'
        }]
    }]
}, {
    name: 'Country5',
    states: [{
        name: 'c5_State4',
        cities: [{
            name: 'c5_s4_City3',
            population: '58985'
        }, {
            name: 'c5_s4_City1',
            population: '326973'
        }, {
            name: 'c5_s4_City2',
            population: '325280'
        }, {
            name: 'c5_s4_City4',
            population: '401752'
        }]
    }, {
        name: 'c5_State5',
        cities: [{
            name: 'c5_s5_City1',
            population: '326215'
        }, {
            name: 'c5_s5_City4',
            population: '243803'
        }, {
            name: 'c5_s5_City3',
            population: '258390'
        }, {
            name: 'c5_s5_City2',
            population: '104685'
        }]
    }, {
        name: 'c5_State1',
        cities: [{
            name: 'c5_s1_City2',
            population: '253002'
        }, {
            name: 'c5_s1_City4',
            population: '234525'
        }, {
            name: 'c5_s1_City3',
            population: '7100'
        }, {
            name: 'c5_s1_City1',
            population: '5387'
        }]
    }, {
        name: 'c5_State3',
        cities: [{
            name: 'c5_s3_City1',
            population: '355018'
        }, {
            name: 'c5_s3_City3',
            population: '224486'
        }, {
            name: 'c5_s3_City4',
            population: '442290'
        }, {
            name: 'c5_s3_City2',
            population: '101298'
        }]
    }, {
        name: 'c5_State2',
        cities: [{
            name: 'c5_s2_City2',
            population: '18079'
        }, {
            name: 'c5_s2_City1',
            population: '278390'
        }, {
            name: 'c5_s2_City4',
            population: '238210'
        }, {
            name: 'c5_s2_City3',
            population: '472739'
        }]
    }]
}];
console.log(countries);